[package]
name = "grib"
version = "0.5.0"
authors = ["Noritada Kobayashi <noritada.kobayashi@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "GRIB format parser for Rust"
readme = "README.md"
repository = "https://github.com/noritada/grib-rs"
homepage = "https://github.com/noritada/grib-rs"
categories = ["science"]
keywords = ["GRIB", "weather", "meteorology"]

[dependencies]
anyhow = "1"
chrono = "0.4.20" # avoiding vulnerable time 0.1 dependency
clap = { version = "3.2", features = ["cargo"] }
console = "0.15"
num = "0.4"
num_enum = "0.5"
once_cell = "1.13"
openjpeg-sys = "1.0.5" # avoiding 1.0.2/1.0.4
regex = "1.6"

[target.'cfg(unix)'.dependencies]
pager = "0.16"
which = "4"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
tempfile = "3"
xz2 = "0.1"

[build-dependencies]
grib-build = { path = "gen", version = "0.3.0" }
