[package]
name = "grib"
version = "0.5.0"
authors = ["Noritada Kobayashi <noritada.kobayashi@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "GRIB format parser for Rust"
readme = "README.md"
repository = "https://github.com/noritada/grib-rs"
homepage = "https://github.com/noritada/grib-rs"
categories = ["science"]
keywords = ["GRIB", "weather", "meteorology"]

[workspace]
members = ["gen", "cli"]

[dependencies]
chrono = "0.4.20" # avoiding vulnerable time 0.1 dependency
num = "0.4"
num_enum = "0.5"
openjpeg-sys = "1.0.5" # avoiding 1.0.2/1.0.4

[build-dependencies]
grib-build = { path = "gen", version = "0.3.0" }
