[package]
name = "grib-build"
version = "0.3.0"
authors = ["Noritada Kobayashi <noritada.kobayashi@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Data definition parsers for the grib crate, used internally as a build-dependency"
readme = "../README.md"
repository = "https://github.com/noritada/grib-rs"
homepage = "https://github.com/noritada/grib-rs"

[dependencies]
csv = "1"
serde = { version = "1", features = ["derive"] }
